# Generated by Django 5.0.1 on 2024-04-28 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_auser_sex'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_direct_messages', to='account.auser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
