# Generated by Django 5.0.1 on 2024-07-20 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_auser_sex'),
        ('message', '0003_initial'),
        ('tool', '0008_rename_channelofio_channelofchat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directmessage',
            options={'ordering': ['time_sent']},
        ),
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'ordering': ['time_sent']},
        ),
        migrations.RenameField(
            model_name='directmessage',
            old_name='last_modified_date',
            new_name='last_edit',
        ),
        migrations.RenameField(
            model_name='directmessage',
            old_name='date_sent',
            new_name='time_sent',
        ),
        migrations.RenameField(
            model_name='groupmessage',
            old_name='last_modified_date',
            new_name='last_edit',
        ),
        migrations.RenameField(
            model_name='groupmessage',
            old_name='date_sent',
            new_name='time_sent',
        ),
        migrations.AddField(
            model_name='directmessage',
            name='_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_msgs', to='tool.channelofchat'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='mentioned_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentioned_msgs', to='account.auser'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_group_messages', to='account.auser'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='tool_used',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_direct_messages', to='account.auser'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_direct_messages', to='account.auser'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_group_messages', to='account.auser'),
        ),
    ]
