# Generated by Django 5.0.1 on 2024-07-21 07:04

from django.db import migrations
from message import util

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("message", "DirectMessage")
    for row in MyModel.objects.all():
        row.urlCode = util.getDirectMessageCode
        row.save(update_fields=["urlCode"])

    MyModel = apps.get_model("message", "GroupMessage")
    for row in MyModel.objects.all():
        row.urlCode = util.getGroupMessageCode
        row.save(update_fields=["urlCode"])

class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_directmessage_urlcode_groupmessage_urlcode'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        
    ]
