# Generated by Django 5.0.1 on 2024-07-21 07:04

from django.db import migrations, models
import message

class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_auto_20240721_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='urlCode',
            field=models.PositiveBigIntegerField(db_index=True, default=message.util.getDirectMessageCode, unique=True),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='urlCode',
            field=models.PositiveBigIntegerField(db_index=True, default=message.util.getGroupMessageCode, unique=True),
        ),
    ]
