# Generated by Django 5.0.1 on 2024-07-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_auto_20240721_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='content',
        ),
        migrations.AddField(
            model_name='directmessage',
            name='contents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='contents',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
