# Generated by Django 5.0.1 on 2024-07-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_remove_directmessage_id_remove_groupmessage_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='channel',
        ),
    ]
