# Generated by Django 5.0.1 on 2024-07-26 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0010_remove_groupmessage_channel'),
        ('tool', '0027_remove_channelofchat_id_remove_channelofvoice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_msgs', to='tool.channelofchat'),
        ),
    ]
