# Generated by Django 5.0.1 on 2024-07-26 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_buser'),
        ('message', '0011_groupmessage_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_direct_messages2', to='account.buser'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_direct_messages2', to='account.buser'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='mentioned_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentioned_msgs2', to='account.buser'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_group_messages2', to='account.buser'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_group_messages2', to='account.buser'),
        ),
    ]
