# Generated by Django 5.0.1 on 2024-07-26 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_delete_buser'),
        ('message', '0013_alter_directmessage_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='mentioned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentioned_msgs2', to='account.auser'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_group_messages2', to='account.auser'),
        ),
    ]
