# Generated by Django 5.0.1 on 2024-08-06 03:55

import django.db.models.deletion
import project.snowflake
from django.db import migrations, models
import json

def forwards(apps, schema_editor):
    # Get the models
    DirectMessage = apps.get_model('message', 'DirectMessage')
    GroupMessage = apps.get_model('message', 'GroupMessage')
    Message = apps.get_model('message', 'Message')

    # Create Message instances for DirectMessage instances
    for dm in DirectMessage.objects.all():
        message = Message.objects.create(
            # id=dm.id,  # Set the primary key to match the DirectMessage id
            contents=dm.contents,
            time_sent=dm.time_sent,
            is_read=dm.is_read,
            is_edited=dm.is_edited,
            last_edit=dm.last_edit,
            _type=dm._type,
            urlCode=dm.urlCode
        )
        dm.message_ptr_id = message.urlCode
        dm.save()

    # Create Message instances for GroupMessage instances
    for gm in GroupMessage.objects.all():
        message = Message.objects.create(
            # id=gm.id,  # Set the primary key to match the GroupMessage id
            contents=gm.contents,
            time_sent=gm.time_sent,
            is_read=gm.is_read,
            is_edited=gm.is_edited,
            last_edit=gm.last_edit,
            _type=gm._type,
            urlCode=gm.urlCode
        )
        gm.message_ptr_id = message.urlCode
        gm.save()

def backwards(apps, schema_editor):
    # No need to implement backwards, as data can't be reverted automatically
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('message', '0015_alter_directmessage_urlcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('contents', models.JSONField(blank=True, null=True)),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('last_edit', models.DateTimeField(auto_now_add=True)),
                ('_type', models.CharField(blank=True, max_length=20, null=True)),
                ('urlCode', models.PositiveBigIntegerField(db_index=True, default=project.snowflake.getMessageMessageSnowflakeID, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['time_sent'],
            },
        ),
        migrations.AddField(
            model_name='directmessage',
            name='message_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, null=True, serialize=False, to='message.message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='message_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, null=True, serialize=False, to='message.message'),
            preserve_default=False,
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name='directmessage',
            name='message_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='message.message'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='message_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='message.message'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='_type',
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='last_edit',
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='time_sent',
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='urlCode',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='_type',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='last_edit',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='time_sent',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='urlCode',
        ),
    ]
