# Generated by Django 5.0.1 on 2024-08-09 04:14

import django.utils.timezone
import project.snowflake
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0016_message_remove_directmessage__type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'ordering': ['urlCode']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['urlCode']},
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='message_ptr',
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='contents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='last_edit',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='time_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='urlCode',
            field=models.PositiveBigIntegerField(default=project.snowflake.getMessageMessageSnowflakeID, null=True),
        ),
    ]
