# Generated by Django 5.0.1 on 2024-08-09 04:15

import project.snowflake
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0017_alter_groupmessage_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='id',
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='urlCode',
            field=models.PositiveBigIntegerField(db_index=True, default=project.snowflake.getMessageMessageSnowflakeID, primary_key=True, serialize=False, unique=True),
        ),
    ]
