# Generated by Django 5.0.1 on 2024-08-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0019_rename_groupmessage_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='contents',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
