# Generated by Django 5.1.1 on 2024-09-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0020_alter_message_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='state',
            field=models.CharField(choices=[('0', 'pending'), ('1', 'active'), ('2', 'archived')], default='0', max_length=2, verbose_name="\n        type:\n        [\n            ('0', 'pending'),\n            ('1', 'active'),\n            ('2', 'archived')\n        ]\n        "),
        ),
    ]
