# Generated by Django 5.1.1 on 2025-06-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0021_chatmessage_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='state',
            field=models.CharField(choices=[('0', 'pending'), ('1', 'active'), ('2', 'archived')], default='0', max_length=2, verbose_name="\n        state:\n        [\n            ('0', 'pending'),\n            ('1', 'active'),\n            ('2', 'archived')\n        ]\n        "),
        ),
    ]
