# Generated by Django 5.1.1 on 2025-07-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0022_alter_chatmessage_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='contents',
            field=models.JSONField(default=dict),
        ),
    ]
