# Generated by Django 5.1.1 on 2025-07-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_auser_additional'),
        ('message', '0023_alter_chatmessage_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='mentioned_user',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, related_name='mentioned_msgs2', to='account.auser'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='mentions_all',
            field=models.BooleanField(default=False),
        ),
    ]
