# Generated by Django 5.1.1 on 2025-07-01 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0025_chatmessage_content_text_chatmessage_has_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='mention_count',
        ),
    ]
