# Generated by Django 5.0.1 on 2024-03-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_cover_user_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='logo',
            new_name='avatar',
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('1', '女'), ('0', '男')], default='隐藏', max_length=2),
        ),
    ]
