# Generated by Django 5.0.1 on 2024-03-18 08:54

import account.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_logo_user_avatar_alter_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('0', '男'), ('1', '女')], default='隐藏', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='urlCode',
            field=models.PositiveBigIntegerField(db_index=True, default=account.util.getUserCode, unique=True),
        ),
    ]
