# Generated by Django 5.0.1 on 2024-03-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_sex_alter_user_urlcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('1', '女'), ('0', '男')], default='隐藏', max_length=2),
        ),
    ]
