# Generated by Django 4.2.10 on 2024-03-31 11:03

import account.models
import account.util
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0010_alter_user_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='AUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default='some_user', max_length=20)),
                ('urlCode', models.PositiveBigIntegerField(db_index=True, default=account.util.getUserCode, unique=True)),
                ('sex', models.CharField(choices=[('0', '男'), ('1', '女')], default='隐藏', max_length=2)),
                ('age', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('info', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('additional', models.JSONField(blank=True, default=None, null=True)),
                ('cover', models.ImageField(blank=True, default='', upload_to=account.models.AUser.cover_dir_path)),
                ('avatar', models.ImageField(blank=True, default='', upload_to=account.models.AUser.avatar_dir_path)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='', upload_to=account.models.AUser.avatar_dir_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to=account.models.AUser.cover_dir_path),
        ),
    ]
