# Generated by Django 5.0.1 on 2024-03-29 10:22

import account.models
import account.util
import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_options_alter_user_managers_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default='some_user', max_length=20)),
                ('urlCode', models.PositiveBigIntegerField(db_index=True, default=account.util.getUserCode, unique=True)),
                ('sex', models.CharField(choices=[('1', '女'), ('0', '男')], default='隐藏', max_length=2)),
                ('age', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('info', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('additional', models.JSONField(blank=True, default=None, null=True)),
                ('cover', models.ImageField(blank=True, default='', upload_to=account.models.User.cover_dir_path)),
                ('avatar', models.ImageField(blank=True, default='', upload_to=account.models.User.avatar_dir_path)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_ptr',
        ),
    ]
