# Generated by Django 4.2.10 on 2024-03-31 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auser_alter_user_avatar_alter_user_cover'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
