# Generated by Django 5.0.1 on 2024-05-09 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_auser_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auser',
            name='sex',
        ),
    ]
