# Generated by Django 5.0.1 on 2024-07-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_buser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AUser',
        ),
    ]
