# Generated by Django 5.0.1 on 2024-07-26 10:23

import account.models
import django.contrib.auth.models
import django.db.models.deletion
import project.snowflake
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_delete_auser'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default='some_user', max_length=20)),
                ('urlCode', models.PositiveBigIntegerField(db_index=True, default=project.snowflake.getAccountAUserSnowflakeID, primary_key=True, serialize=False, unique=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('info', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('additional', models.JSONField(blank=True, default=None, null=True)),
                ('cover', models.ImageField(blank=True, default='', upload_to=account.models.AUser.cover_dir_path)),
                ('avatar', models.ImageField(blank=True, default='', upload_to=account.models.AUser.avatar_dir_path)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='buser',
            name='avatar',
            field=models.ImageField(blank=True, default='', upload_to=account.models.AUser.avatar_dir_path),
        ),
        migrations.AlterField(
            model_name='buser',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to=account.models.AUser.cover_dir_path),
        ),
    ]
