# Generated by Django 5.0.1 on 2024-07-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auser_alter_buser_avatar_alter_buser_cover'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BUser',
        ),
    ]
