# Generated by Django 5.0.7 on 2024-08-10 07:22

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_auser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auser',
            name='avatar',
            field=models.ImageField(blank=True, default='default/user/user.svg', upload_to=account.models.AUser.avatar_dir_path),
        ),
    ]
