# Generated by Django 5.1.1 on 2024-09-14 03:38

import UtilGlobal.validator.FieldFile
import account.models
import media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_auser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auser',
            name='avatar',
            field=models.ImageField(blank=True, default='', storage=media.models.MediaFileSystemStorage, upload_to=account.models.AUser.avatar_dir_path, validators=[UtilGlobal.validator.FieldFile.imagefile_validator]),
        ),
        migrations.AlterField(
            model_name='auser',
            name='cover',
            field=models.ImageField(blank=True, default='', storage=media.models.MediaFileSystemStorage, upload_to=account.models.AUser.cover_dir_path, validators=[UtilGlobal.validator.FieldFile.imagefile_validator]),
        ),
    ]
