# Generated by Django 5.1.1 on 2025-06-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='used_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
