# Generated by Django 5.1.1 on 2025-07-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_emailverificationcode_used_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auser',
            name='additional',
            field=models.JSONField(default=dict),
        ),
    ]
