# Generated by Django 5.0.7 on 2024-08-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='name',
            field=models.CharField(default='2', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='v',
            field=models.CharField(default='2', max_length=500),
            preserve_default=False,
        ),
    ]
