# Generated by Django 5.0.1 on 2024-02-18 05:30

import django.db.models.deletion
import django.utils.timezone
import tool.models
import tool.util.model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerAuthorizationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(default='', max_length=512)),
                ('type', models.CharField(choices=[('0', 'binary')], default='0', max_length=2)),
                ('category', models.CharField(choices=[('0', 'General Server Permissions'), ('1', 'Other Permissions')], default='0', max_length=2)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ToolAuthorizationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(default='', max_length=512)),
                ('type', models.CharField(choices=[('0', 'binary')], default='0', max_length=2)),
                ('category', models.CharField(choices=[('0', 'General Tool Permissions'), ('1', 'Membership Permissions'), ('2', 'Other Permissions')], default='0', max_length=2)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ToolServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('urlCode', models.IntegerField(db_index=True, default=tool.util.model.getToolServerCode, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('0', 'destroyed'), ('1', 'public'), ('2', 'private'), ('3', 'archived')], default='1', max_length=2)),
                ('cover', models.ImageField(blank=True, default='', upload_to=tool.models.ToolServer.cover_dir_path)),
                ('logo', models.ImageField(blank=True, default='', upload_to=tool.models.ToolServer.logo_dir_path)),
                ('additional', models.JSONField(default=tool.models.EmptyJson, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_servers', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('urlCode', models.IntegerField(db_index=True, default=tool.util.model.getToolCode, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('0', 'basic'), ('1', 'others')], default='0', max_length=2)),
                ('status', models.CharField(choices=[('0', 'destroyed'), ('1', 'public'), ('2', 'private'), ('3', 'archived')], default='1', max_length=2)),
                ('cover', models.ImageField(blank=True, default='', upload_to=tool.models.Tool.cover_dir_path)),
                ('logo', models.ImageField(blank=True, default='', upload_to=tool.models.Tool.logo_dir_path)),
                ('additional', models.JSONField(default=tool.models.EmptyJson, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='tool.toolserver')),
            ],
        ),
        migrations.CreateModel(
            name='ServerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(default='', max_length=512)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('auth', models.ManyToManyField(related_name='server_roles', to='tool.serverauthorizationlevel')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_roles', to='tool.toolserver')),
            ],
        ),
        migrations.CreateModel(
            name='UserServerAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_value_bool', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('auth_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_server_auths', to='tool.serverauthorizationlevel')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_server_auths', to='tool.serverrole', verbose_name='user role in the server')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_server_auths', to='tool.toolserver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_server_auths', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserToolAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_value_bool', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('auth_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tool_auths', to='tool.toolauthorizationlevel')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tool_auths', to='tool.tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tool_auths', to='account.user')),
            ],
        ),
    ]
