# Generated by Django 5.0.1 on 2024-04-29 02:57

import django.db.models.deletion
import django.utils.timezone
import tool.models
import tool.util.model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_auser_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(default='', max_length=512)),
                ('type', models.CharField(choices=[('0', 'binary')], default='0', max_length=2)),
                ('category', models.CharField(choices=[('0', 'General Server Permissions'), ('1', 'Membership PERMISSIONS'), ('2', 'TEXT CHANNEL PERMISSIONS'), ('3', 'VOICE CHANNEL PERMISSIONS'), ('4', 'EVENTS PERMISSIONS'), ('5', 'ADVANCED PERMISSIONS')], default='0', max_length=3)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryInServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('0', 'chat'), ('1', 'voice')], default='0', max_length=2, verbose_name="\n        type:\n        [\n            ('0', 'chat'),\n            ('1', 'voice'),\n        ]\n        ")),
            ],
        ),
        migrations.CreateModel(
            name='ToolServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('urlCode', models.PositiveBigIntegerField(db_index=True, default=tool.util.model.getToolServerCode, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('0', 'tool'), ('1', 'have fun'), ('2', 'others')], default='0', max_length=2, verbose_name="\n        type:\n        [\n            ('0', 'tool'),\n            ('1', 'have fun'),\n            ('2', 'others')\n        ]\n        ")),
                ('status', models.CharField(choices=[('0', 'destroyed'), ('1', 'public'), ('2', 'private'), ('3', 'archived')], default='1', max_length=2)),
                ('cover', models.ImageField(blank=True, default='', upload_to=tool.models.ToolServer.cover_dir_path)),
                ('logo', models.ImageField(blank=True, default='', upload_to=tool.models.ToolServer.logo_dir_path)),
                ('additional', models.JSONField(blank=True, default=tool.models.getDefaultAdditional, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_servers', to='account.auser')),
            ],
        ),
        migrations.CreateModel(
            name='ToolOfIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('urlCode', models.PositiveBigIntegerField(db_index=True, default=tool.util.model.getToolCode, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('0', 'destroyed'), ('1', 'public'), ('2', 'private'), ('3', 'archived')], default='1', max_length=2)),
                ('cover', models.ImageField(blank=True, default='', upload_to=tool.models.Tool.cover_dir_path)),
                ('logo', models.ImageField(blank=True, default='', upload_to=tool.models.Tool.logo_dir_path)),
                ('additional', models.JSONField(blank=True, default=tool.models.getDefaultAdditional, null=True)),
                ('method_names', models.JSONField(blank=True, default=tool.models.EmptyJson)),
                ('input', models.JSONField(blank=True, default=tool.models.EmptyJson, null=True)),
                ('output', models.JSONField(blank=True, default=tool.models.EmptyJson, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toolofios', to='tool.categoryinserver')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toolofios', to='tool.toolserver')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToolOfChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('urlCode', models.PositiveBigIntegerField(db_index=True, default=tool.util.model.getToolCode, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('0', 'destroyed'), ('1', 'public'), ('2', 'private'), ('3', 'archived')], default='1', max_length=2)),
                ('cover', models.ImageField(blank=True, default='', upload_to=tool.models.Tool.cover_dir_path)),
                ('logo', models.ImageField(blank=True, default='', upload_to=tool.models.Tool.logo_dir_path)),
                ('additional', models.JSONField(blank=True, default=tool.models.getDefaultAdditional, null=True)),
                ('method_names', models.JSONField(blank=True, default=tool.models.EmptyJson)),
                ('bots', models.JSONField(blank=True, default=tool.models.EmptyJson, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toolofchats', to='tool.categoryinserver')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toolofchats', to='tool.toolserver')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(default='', max_length=512)),
                ('auth_value', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('auth', models.ManyToManyField(related_name='server_roles', to='tool.authorizationlevel')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_roles', to='tool.toolserver')),
            ],
        ),
        migrations.AddField(
            model_name='categoryinserver',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tool.toolserver'),
        ),
        migrations.CreateModel(
            name='UserServerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.PositiveIntegerField(default=0)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_server_auths', to='tool.serverrole', verbose_name='user role in the server')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_server_auths', to='tool.toolserver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_server_auths', to='account.auser')),
            ],
        ),
        migrations.CreateModel(
            name='UserToolOfChatRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_toolofchat_auths', to='tool.serverrole', verbose_name='user role in the server')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_toolofchat_auths', to='tool.toolofchat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_toolofchat_auths', to='account.auser')),
            ],
        ),
        migrations.CreateModel(
            name='UserToolOfIORole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_toolofio_auths', to='tool.serverrole', verbose_name='user role in the server')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_toolofio_auths', to='tool.toolofio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_toolofio_auths', to='account.auser')),
            ],
        ),
    ]
