# Generated by Django 5.0.1 on 2024-05-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryinserver',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
