# Generated by Django 5.0.1 on 2024-02-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='type',
            field=models.CharField(choices=[('0', 'basic'), ('1', 'others')], default='0', max_length=3),
        ),
    ]
