# Generated by Django 5.0.1 on 2024-02-07 08:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerAuthorizationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(default='', max_length=512)),
                ('type', models.CharField(choices=[('0', 'binary')], default='0', max_length=2)),
                ('category', models.CharField(choices=[('0', 'General Server Permissions'), ('1', 'Other Permissions')], default='0', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ToolAuthorizationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(default='', max_length=512)),
                ('type', models.CharField(choices=[('0', 'binary')], default='0', max_length=2)),
                ('category', models.CharField(choices=[('0', 'General Tool Permissions'), ('1', 'Membership Permissions'), ('2', 'Other Permissions')], default='0', max_length=2)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='userserverauthorization',
            name='auth_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.serverauthorizationlevel'),
        ),
        migrations.AlterField(
            model_name='usertoolauthorization',
            name='auth_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.toolauthorizationlevel'),
        ),
        migrations.DeleteModel(
            name='ServerAuthorizationLevels',
        ),
        migrations.DeleteModel(
            name='ToolAuthorizationLevels',
        ),
    ]
