# Generated by Django 5.0.1 on 2024-05-01 15:54

import tool.util.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_categoryinserver_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryinserver',
            name='urlCode',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
