# Generated by Django 5.0.1 on 2024-02-07 08:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_serverauthorizationlevel_toolauthorizationlevel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverauthorizationlevel',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
