# Generated by Django 5.0.1 on 2024-02-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_alter_tool_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='type',
            field=models.CharField(choices=[('0', 'blank'), ('1', 'intput & output'), ('2', 'exhibition')], default='0', max_length=2),
        ),
    ]
