# Generated by Django 5.0.1 on 2024-02-18 06:47

import django.db.models.deletion
import tool.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_alter_tool_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolInputAndOutput',
            fields=[
                ('tool_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tool.tool')),
                ('method_names', models.JSONField(default=tool.models.EmptyJson)),
                ('input', models.JSONField(default=tool.models.EmptyJson, null=True)),
                ('output', models.JSONField(default=tool.models.EmptyJson, null=True)),
            ],
            bases=('tool.tool',),
        ),
    ]
