# Generated by Django 5.0.1 on 2024-02-18 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0005_toolinputandoutput'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToolInputAndOutput',
            new_name='ToolOfInputAndOutput',
        ),
    ]
