# Generated by Django 5.0.1 on 2024-07-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_auser_sex'),
        ('tool', '0005_toolofchat_isserverentry_toolofio_isserverentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChannelOfChat',
            new_name='ChannelOfVoice',
        ),
        migrations.RenameModel(
            old_name='UserChannelOfChatRole',
            new_name='UserChannelOfVoiceRole',
        ),
    ]
