# Generated by Django 5.0.1 on 2024-07-12 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_auser_sex'),
        ('tool', '0006_rename_channelofchat_channelofvoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelofio',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channelofchats', to='tool.categoryinserver'),
        ),
        migrations.AlterField(
            model_name='channelofio',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channelofchats', to='tool.server'),
        ),
        migrations.AlterField(
            model_name='channelofvoice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channelofvoices', to='tool.categoryinserver'),
        ),
        migrations.AlterField(
            model_name='channelofvoice',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channelofvoices', to='tool.server'),
        ),
        migrations.AlterField(
            model_name='userchannelofiorole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_channelofchat_auths', to='tool.serverrole', verbose_name='user role in the server'),
        ),
        migrations.AlterField(
            model_name='userchannelofiorole',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_channelofchat_auths', to='tool.channelofio'),
        ),
        migrations.AlterField(
            model_name='userchannelofiorole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_channelofchat_auths', to='account.auser'),
        ),
        migrations.AlterField(
            model_name='userchannelofvoicerole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_channelofvoice_auths', to='tool.serverrole', verbose_name='user role in the server'),
        ),
        migrations.AlterField(
            model_name='userchannelofvoicerole',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_channelofvoice_auths', to='tool.channelofvoice'),
        ),
        migrations.AlterField(
            model_name='userchannelofvoicerole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_channelofvoice_auths', to='account.auser'),
        ),
    ]
