# Generated by Django 5.0.1 on 2024-02-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0006_rename_toolinputandoutput_toolofinputandoutput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverauthorizationlevel',
            name='category',
            field=models.CharField(choices=[('0', 'General Server Permissions'), ('1', 'Membership PERMISSIONS'), ('2', 'TEXT CHANNEL PERMISSIONS'), ('3', 'VOICE CHANNEL PERMISSIONS'), ('4', 'EVENTS PERMISSIONS'), ('5', 'ADVANCED PERMISSIONS')], default='0', max_length=3),
        ),
    ]
