# Generated by Django 5.0.1 on 2024-02-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0007_alter_serverauthorizationlevel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolserver',
            name='type',
            field=models.CharField(choices=[('0', 'tool'), ('1', 'have fun'), ('2', 'others')], default='0', max_length=2),
        ),
    ]
