# Generated by Django 5.0.1 on 2024-02-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0008_alter_toolserver_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='type',
            field=models.CharField(choices=[('0', 'blank'), ('1', 'intput & output'), ('2', 'exhibition'), ('3', 'blog')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='toolserver',
            name='type',
            field=models.CharField(choices=[('0', 'tool'), ('1', 'have fun'), ('2', 'others')], default='0', max_length=2, verbose_name="\n        type:\n        [\n            ('0', 'tool'),\n            ('1', 'have fun'),\n            ('2', 'others')\n        ]\n        "),
        ),
    ]
