# Generated by Django 5.0.1 on 2024-07-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0008_rename_channelofio_channelofchat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userserverrole',
            name='nickname',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
