# Generated by Django 5.0.1 on 2024-02-20 10:01

import tool.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0009_alter_tool_type_alter_toolserver_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='additional',
            field=models.JSONField(blank=True, default=tool.models.EmptyJson, null=True),
        ),
        migrations.AlterField(
            model_name='toolofinputandoutput',
            name='input',
            field=models.JSONField(blank=True, default=tool.models.EmptyJson, null=True),
        ),
        migrations.AlterField(
            model_name='toolofinputandoutput',
            name='method_names',
            field=models.JSONField(blank=True, default=tool.models.EmptyJson),
        ),
        migrations.AlterField(
            model_name='toolofinputandoutput',
            name='output',
            field=models.JSONField(blank=True, default=tool.models.EmptyJson, null=True),
        ),
    ]
