# Generated by Django 5.0.1 on 2024-07-26 06:23

import django.db.models.deletion
import project.snowflake
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0009_userserverrole_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelofchat',
            old_name='input',
            new_name='inputs',
        ),
        migrations.RenameField(
            model_name='channelofchat',
            old_name='output',
            new_name='outputs',
        ),
        migrations.AddField(
            model_name='channelofchat',
            name='server_placeholder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channelofchats_placeholder', to='tool.server', to_field='urlCode'),
        ),
        migrations.AddField(
            model_name='channelofvoice',
            name='server_placeholder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channelofvoices_placeholder', to='tool.server', to_field='urlCode'),
        ),
        migrations.AlterField(
            model_name='server',
            name='urlCode',
            field=models.PositiveBigIntegerField(db_index=True, default=project.snowflake.getToolServerSnowflakeID, unique=True),
        ),
    ]
