# Generated by Django 5.0.1 on 2024-02-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0010_alter_tool_additional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
