# Generated by Django 5.0.1 on 2024-07-26 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0010_rename_input_channelofchat_inputs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelofchat',
            name='server',
        ),
        migrations.RemoveField(
            model_name='channelofvoice',
            name='server',
        ),
    ]
