# Generated by Django 5.0.1 on 2024-02-21 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0011_alter_tool_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServerAuthorizationLevel',
            new_name='AuthorizationLevel',
        ),
    ]
