# Generated by Django 5.0.1 on 2024-02-21 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0012_rename_serverauthorizationlevel_authorizationlevel'),
        ('user', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserServerAuthorization',
            new_name='UserServerRole',
        ),
        migrations.RenameModel(
            old_name='UserToolAuthorization',
            new_name='UserToolRole',
        ),
        migrations.DeleteModel(
            name='ToolAuthorizationLevel',
        ),
        migrations.AlterField(
            model_name='usertoolrole',
            name='auth_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tool_auths', to='tool.authorizationlevel'),
        ),
    ]
