# Generated by Django 5.0.1 on 2024-07-26 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0012_rename_server_placeholder_channelofchat_server_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchannelofchatrole',
            old_name='tool',
            new_name='channel',
        ),
        migrations.RenameField(
            model_name='userchannelofvoicerole',
            old_name='tool',
            new_name='channel',
        ),
        migrations.AddField(
            model_name='serverrole',
            name='server_placeholder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_roles_placeholder', to='tool.server', to_field='urlCode'),
        ),
        migrations.AddField(
            model_name='userserverrole',
            name='server_placeholder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_server_auths_placeholder', to='tool.server', to_field='urlCode'),
        ),
        migrations.AlterField(
            model_name='channelofchat',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channelofchats', to='tool.server', to_field='urlCode'),
        ),
        migrations.AlterField(
            model_name='channelofvoice',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channelofvoices', to='tool.server', to_field='urlCode'),
        ),
    ]
