# Generated by Django 5.0.1 on 2024-02-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0013_rename_userserverauthorization_userserverrole_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userserverrole',
            name='auth_type',
        ),
        migrations.RemoveField(
            model_name='userserverrole',
            name='auth_value_bool',
        ),
        migrations.RemoveField(
            model_name='usertoolrole',
            name='auth_type',
        ),
        migrations.RemoveField(
            model_name='usertoolrole',
            name='auth_value_bool',
        ),
        migrations.AddField(
            model_name='serverrole',
            name='auth_value',
            field=models.BooleanField(default=True),
        ),
    ]
