# Generated by Django 5.0.1 on 2024-07-26 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0013_rename_tool_userchannelofchatrole_channel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverrole',
            name='server',
        ),
        migrations.RemoveField(
            model_name='userserverrole',
            name='server',
        ),
    ]
