# Generated by Django 5.0.1 on 2024-02-21 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0014_remove_userserverrole_auth_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryInServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tool.toolserver')),
            ],
        ),
    ]
