# Generated by Django 5.0.1 on 2024-07-26 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0014_remove_serverrole_server_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverrole',
            name='server_placeholder',
        ),
        migrations.RemoveField(
            model_name='userserverrole',
            name='server_placeholder',
        ),
        migrations.AddField(
            model_name='serverrole',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_roles', to='tool.server', to_field='urlCode'),
        ),
        migrations.AddField(
            model_name='userserverrole',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_server_auths', to='tool.server', to_field='urlCode'),
        ),
    ]
