# Generated by Django 5.0.1 on 2024-02-21 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0015_categoryinserver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='type',
        ),
    ]
