# Generated by Django 5.0.1 on 2024-07-26 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0015_remove_serverrole_server_placeholder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryinserver',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories_ph', to='tool.server', to_field='urlCode'),
        ),
    ]
