# Generated by Django 5.0.1 on 2024-02-21 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0016_remove_tool_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='tool.categoryinserver'),
        ),
    ]
