# Generated by Django 5.0.1 on 2024-07-26 08:35

import django.db.models.deletion
import django.utils.timezone
import project.snowflake
import tool.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_auser_sex'),
        ('tool', '0017_serverph_alter_categoryinserver_server_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverph',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to=tool.models.Server.cover_dir_path),
        ),
        migrations.AlterField(
            model_name='serverph',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to=tool.models.Server.logo_dir_path),
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('urlCode', models.PositiveBigIntegerField(db_index=True, default=project.snowflake.getToolServerSnowflakeID, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('0', 'tool'), ('1', 'have fun'), ('2', 'others')], default='0', max_length=2, verbose_name="\n        type:\n        [\n            ('0', 'tool'),\n            ('1', 'have fun'),\n            ('2', 'others')\n        ]\n        ")),
                ('status', models.CharField(choices=[('0', 'destroyed'), ('1', 'public'), ('2', 'private'), ('3', 'archived')], default='1', max_length=2)),
                ('cover', models.ImageField(blank=True, default='', upload_to=tool.models.Server.cover_dir_path)),
                ('logo', models.ImageField(blank=True, default='', upload_to=tool.models.Server.logo_dir_path)),
                ('additional', models.JSONField(blank=True, default=tool.models.getDefaultAdditional, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_servers', to='account.auser')),
            ],
        ),
    ]
