# Generated by Django 5.0.1 on 2024-02-21 02:19

from django.db import migrations

def set_default_category(apps, schema_editor):
    Category = apps.get_model('tool', 'CategoryInServer')
    Book = apps.get_model('tool', 'Tool')
    default_category = Category.objects.first()  # Get the first category
    if default_category:
        Book.objects.filter(type__isnull=True).update(type=default_category)


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0017_tool_type'),
    ]

    operations = [
        migrations.RunPython(set_default_category),
    ]
