# Generated by Django 5.0.1 on 2024-02-21 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0018_auto_20240221_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='tool.categoryinserver'),
        ),
    ]
