# Generated by Django 5.0.1 on 2024-07-26 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0018_alter_serverph_cover_alter_serverph_logo_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryinserver',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tool.server'),
        ),
        migrations.AlterField(
            model_name='channelofchat',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channelofchats', to='tool.server'),
        ),
        migrations.AlterField(
            model_name='channelofvoice',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channelofvoices', to='tool.server'),
        ),
        migrations.AlterField(
            model_name='serverrole',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_roles', to='tool.server'),
        ),
        migrations.AlterField(
            model_name='userserverrole',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_server_auths', to='tool.server'),
        ),
    ]
