# Generated by Django 5.0.1 on 2024-02-21 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0019_alter_tool_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='type',
            new_name='category',
        ),
    ]
