# Generated by Django 5.0.1 on 2024-07-26 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0019_alter_categoryinserver_server_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServerPH',
        ),
    ]
