# Generated by Django 5.0.1 on 2024-02-21 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0020_rename_type_tool_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoolrole',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tool_auths', to='tool.serverrole', verbose_name='user role in the server'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='additional',
            field=models.JSONField(blank=True, default={'type': 'ToolTypical'}, null=True),
        ),
        migrations.AlterField(
            model_name='toolserver',
            name='additional',
            field=models.JSONField(blank=True, default={'type': {}}, null=True),
        ),
        migrations.AlterField(
            model_name='toolserver',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
