# Generated by Django 5.0.1 on 2024-07-26 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0020_delete_serverph'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelofchat',
            name='category2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channelofchats2', to='tool.categoryinserver', to_field='urlCode'),
        ),
        migrations.AddField(
            model_name='channelofvoice',
            name='category2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channelofvoices2', to='tool.categoryinserver', to_field='urlCode'),
        ),
    ]
