# Generated by Django 5.0.1 on 2024-07-26 09:10

import django.db.models.deletion
import tool.util.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0021_channelofchat_category2_channelofvoice_category2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryInServer2',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('0', 'chat'), ('1', 'voice')], default='0', max_length=2, verbose_name="\n        type:\n        [\n            ('0', 'chat'),\n            ('1', 'voice'),\n        ]\n        ")),
                ('urlCode', models.PositiveBigIntegerField(db_index=True, default=tool.util.model.getCategoryCode, primary_key=True, serialize=False, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories_ph', to='tool.server')),
            ],
        ),
    ]
