# Generated by Django 5.0.1 on 2024-02-21 09:20

import django.db.models.deletion
import tool.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0021_usertoolrole_role_alter_tool_additional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoolrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tool_auths', to='tool.serverrole', verbose_name='user role in the server'),
        ),
    ]
