# Generated by Django 5.0.1 on 2024-07-26 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0022_categoryinserver2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelofchat',
            name='category',
        ),
        migrations.RemoveField(
            model_name='channelofvoice',
            name='category',
        ),
        migrations.AlterField(
            model_name='channelofchat',
            name='category2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channelofchats2', to='tool.categoryinserver2'),
        ),
        migrations.AlterField(
            model_name='channelofvoice',
            name='category2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channelofvoices2', to='tool.categoryinserver2'),
        ),
    ]
