# Generated by Django 5.0.1 on 2024-02-22 02:42

import django.db.models.deletion
import tool.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0022_alter_usertoolrole_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolOfChat',
            fields=[
                ('tool_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tool.tool')),
                ('method_names', models.JSONField(blank=True, default=tool.models.EmptyJson)),
                ('bots', models.JSONField(blank=True, default=tool.models.EmptyJson, null=True)),
            ],
            bases=('tool.tool',),
        ),
    ]
