# Generated by Django 5.0.1 on 2024-02-22 08:49

import tool.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0023_toolofchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryinserver',
            name='type',
            field=models.CharField(choices=[('0', 'chat'), ('1', 'voice')], default='0', max_length=2, verbose_name="\n        type:\n        [\n            ('0', 'chat'),\n            ('1', 'voice'),\n        ]\n        "),
        ),
        migrations.AlterField(
            model_name='tool',
            name='additional',
            field=models.JSONField(blank=True, default=tool.models.getDefaultAdditional, null=True),
        ),
        migrations.AlterField(
            model_name='toolserver',
            name='additional',
            field=models.JSONField(blank=True, default=tool.models.getDefaultAdditional, null=True),
        ),
    ]
