# Generated by Django 5.0.1 on 2024-07-26 09:16

import django.db.models.deletion
import tool.util.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0024_delete_categoryinserver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelofchat',
            name='category2',
        ),
        migrations.RemoveField(
            model_name='channelofvoice',
            name='category2',
        ),
        migrations.CreateModel(
            name='CategoryInServer',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('0', 'chat'), ('1', 'voice')], default='0', max_length=2, verbose_name="\n        type:\n        [\n            ('0', 'chat'),\n            ('1', 'voice'),\n        ]\n        ")),
                ('urlCode', models.PositiveBigIntegerField(db_index=True, default=tool.util.model.getCategoryCode, primary_key=True, serialize=False, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tool.server')),
            ],
        ),
        migrations.AddField(
            model_name='channelofchat',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channelofchats', to='tool.categoryinserver'),
        ),
        migrations.AddField(
            model_name='channelofvoice',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channelofvoices', to='tool.categoryinserver'),
        ),
        migrations.DeleteModel(
            name='CategoryInServer2',
        ),
    ]
