# Generated by Django 5.0.1 on 2024-07-26 09:23

import project.snowflake
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0025_remove_channelofchat_category2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchannelofvoicerole',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='userchannelofvoicerole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userchannelofvoicerole',
            name='user',
        ),
        migrations.AlterField(
            model_name='channelofchat',
            name='urlCode',
            field=models.PositiveBigIntegerField(db_index=True, default=project.snowflake.getToolChannelOfChatSnowflakeID, unique=True),
        ),
        migrations.AlterField(
            model_name='channelofvoice',
            name='urlCode',
            field=models.PositiveBigIntegerField(db_index=True, default=project.snowflake.getToolChannelOfChatSnowflakeID, unique=True),
        ),
        migrations.DeleteModel(
            name='UserChannelOfChatRole',
        ),
        migrations.DeleteModel(
            name='UserChannelOfVoiceRole',
        ),
    ]
