# Generated by Django 5.0.1 on 2024-03-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0025_alter_tool_urlcode_alter_toolserver_urlcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userserverrole',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
