# Generated by Django 5.0.1 on 2024-07-26 09:25

import project.snowflake
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0026_remove_userchannelofvoicerole_channel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelofchat',
            name='id',
        ),
        migrations.RemoveField(
            model_name='channelofvoice',
            name='id',
        ),
        migrations.AlterField(
            model_name='channelofchat',
            name='urlCode',
            field=models.PositiveBigIntegerField(db_index=True, default=project.snowflake.getToolChannelOfChatSnowflakeID, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='channelofvoice',
            name='urlCode',
            field=models.PositiveBigIntegerField(db_index=True, default=project.snowflake.getToolChannelOfChatSnowflakeID, primary_key=True, serialize=False, unique=True),
        ),
    ]
