# Generated by Django 4.2.10 on 2024-03-31 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auser_alter_user_avatar_alter_user_cover'),
        ('tool', '0026_userserverrole_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolserver',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_servers', to='account.auser'),
        ),
        migrations.AlterField(
            model_name='userserverrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_server_auths', to='account.auser'),
        ),
        migrations.AlterField(
            model_name='usertoolrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tool_auths', to='account.auser'),
        ),
    ]
