# Generated by Django 5.0.1 on 2024-04-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0027_alter_toolserver_owner_alter_userserverrole_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userserverrole',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
