# Generated by Django 5.0.1 on 2024-04-29 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0028_alter_userserverrole_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToolOfInputAndOutput',
            new_name='ToolOfIO',
        ),
    ]
