# Generated by Django 5.0.1 on 2024-07-26 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_buser'),
        ('tool', '0028_userchannelofchatrole_userchannelofvoicerole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_servers', to='account.buser'),
        ),
        migrations.AlterField(
            model_name='userchannelofchatrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_channelofchat_auths', to='account.buser'),
        ),
        migrations.AlterField(
            model_name='userchannelofvoicerole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_channelofvoice_auths', to='account.buser'),
        ),
        migrations.AlterField(
            model_name='userserverrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_server_auths', to='account.buser'),
        ),
    ]
