# Generated by Django 5.0.1 on 2024-07-26 09:59

import project.snowflake
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0029_alter_server_owner_alter_userchannelofchatrole_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryinserver',
            name='urlCode',
            field=models.PositiveBigIntegerField(db_index=True, default=project.snowflake.getToolCategoryInServerSnowflakeID, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='channelofvoice',
            name='urlCode',
            field=models.PositiveBigIntegerField(db_index=True, default=project.snowflake.getToolChannelOfVoiceSnowflakeID, primary_key=True, serialize=False, unique=True),
        ),
    ]
