# Generated by Django 5.0.1 on 2024-07-26 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auser_alter_buser_avatar_alter_buser_cover'),
        ('tool', '0030_alter_categoryinserver_urlcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_servers', to='account.auser'),
        ),
        migrations.AlterField(
            model_name='userchannelofchatrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_channelofchat_auths', to='account.auser'),
        ),
        migrations.AlterField(
            model_name='userchannelofvoicerole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_channelofvoice_auths', to='account.auser'),
        ),
        migrations.AlterField(
            model_name='userserverrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_server_auths', to='account.auser'),
        ),
    ]
