# Generated by Django 5.0.1 on 2024-07-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0031_alter_server_owner_alter_userchannelofchatrole_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userserverrole',
            name='server',
        ),
    ]
