# Generated by Django 5.0.1 on 2024-08-09 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0033_channelofchat_is_dm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelofchat',
            options={'ordering': ['urlCode']},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['urlCode']},
        ),
    ]
