# Generated by Django 5.1.1 on 2024-09-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0035_remove_serverrole_auth_alter_serverrole_auth_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverrole',
            name='description',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
