# Generated by Django 5.1.1 on 2024-09-14 03:38

import UtilGlobal.validator.FieldFile
import media.models
import tool.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0036_alter_serverrole_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='cover',
            field=models.ImageField(blank=True, default='', storage=media.models.MediaFileSystemStorage, upload_to=tool.models.Server.cover_dir_path, validators=[UtilGlobal.validator.FieldFile.imagefile_validator]),
        ),
        migrations.AlterField(
            model_name='server',
            name='logo',
            field=models.ImageField(blank=True, default='', storage=media.models.MediaFileSystemStorage, upload_to=tool.models.Server.logo_dir_path, validators=[UtilGlobal.validator.FieldFile.imagefile_validator]),
        ),
    ]
