# Generated by Django 5.1.1 on 2024-10-22 08:30

import UtilGlobal.validator.FieldFile
import media.models
import tool.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0037_alter_server_cover_alter_server_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='scaled_logo',
            field=models.ImageField(blank=True, default='', storage=media.models.MediaFileSystemStorage, upload_to=tool.models.Server.scaled_logo_dir_path, validators=[UtilGlobal.validator.FieldFile.imagefile_validator]),
        ),
    ]
