# Generated by Django 5.1.1 on 2025-02-05 13:38

import django.db.models.deletion
import project.snowflake
import tool.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0038_server_scaled_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolInChannelOfChat',
            fields=[
                ('display_name', models.CharField(max_length=64)),
                ('function_name', models.CharField(max_length=64)),
                ('urlCode', models.PositiveBigIntegerField(db_index=True, default=project.snowflake.getToolSnowflakeID, primary_key=True, serialize=False, unique=True)),
                ('params', models.JSONField(default=tool.models.EmptyJson)),
                ('res', models.JSONField(default=tool.models.EmptyJson)),
                ('data', models.JSONField(default=tool.models.EmptyJson)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='tool.channelofchat')),
            ],
        ),
    ]
