# Generated by Django 5.1.1 on 2025-02-05 13:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0039_toolinchannelofchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolinchannelofchat',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
