# Generated by Django 5.1.1 on 2025-02-05 13:45

import tool.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0040_toolinchannelofchat_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolinchannelofchat',
            name='data',
            field=models.JSONField(blank=True, default=tool.models.EmptyJson),
        ),
    ]
