# Generated by Django 5.1.1 on 2025-02-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0041_alter_toolinchannelofchat_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolinchannelofchat',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
