# Generated by Django 5.1.1 on 2025-05-05 09:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auser_scaled_avatar'),
        ('tool', '0042_toolinchannelofchat_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_duration_minutes', models.PositiveIntegerField(default=10080)),
                ('max_uses', models.PositiveIntegerField(default=0)),
                ('remain_uses', models.PositiveIntegerField(default=0)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_codes', to='tool.server')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invitations', to='account.auser')),
            ],
        ),
    ]
