# Generated by Django 5.1.1 on 2025-07-01 05:55

import tool.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0043_invitationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelofchat',
            name='additional',
            field=models.JSONField(default=tool.models.getDefaultAdditional),
        ),
        migrations.AlterField(
            model_name='channelofchat',
            name='inputs',
            field=models.JSONField(default=tool.models.EmptyJson),
        ),
        migrations.AlterField(
            model_name='channelofchat',
            name='method_names',
            field=models.JSONField(default=tool.models.EmptyJson),
        ),
        migrations.AlterField(
            model_name='channelofchat',
            name='outputs',
            field=models.JSONField(default=tool.models.EmptyJson),
        ),
        migrations.AlterField(
            model_name='channelofvoice',
            name='additional',
            field=models.JSONField(default=tool.models.getDefaultAdditional),
        ),
        migrations.AlterField(
            model_name='channelofvoice',
            name='bots',
            field=models.JSONField(default=tool.models.EmptyJson),
        ),
        migrations.AlterField(
            model_name='channelofvoice',
            name='method_names',
            field=models.JSONField(default=tool.models.EmptyJson),
        ),
        migrations.AlterField(
            model_name='server',
            name='additional',
            field=models.JSONField(default=tool.models.getDefaultAdditional),
        ),
        migrations.AlterField(
            model_name='toolinchannelofchat',
            name='data',
            field=models.JSONField(default=tool.models.EmptyJson),
        ),
    ]
