# Generated by Django 5.1.1 on 2025-07-05 10:37

from django.db import migrations


def migrate_contents_field(apps, schema_editor):
    """Transform contents field from list format to dict format"""
    ChatMessage = apps.get_model('message', 'ChatMessage')
    
    for message in ChatMessage.objects.all():
        contents = message.contents
        
        # If contents is a list, wrap it in the new dict format
        if isinstance(contents, list):
            message.contents = {
                "version": "0.10.0",
                "block": contents
            }
            message.save()
        # If contents is already a dict, leave it as is


def reverse_migrate_contents_field(apps, schema_editor):
    """Reverse the migration by extracting the block from dict format"""
    ChatMessage = apps.get_model('message', 'ChatMessage')
    
    for message in ChatMessage.objects.all():
        contents = message.contents
        
        # If contents is a dict with the expected structure, extract the block
        if isinstance(contents, dict) and "block" in contents:
            message.contents = contents["block"]
            message.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0044_alter_channelofchat_additional_and_more'),
        ('message', '__latest__'),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_contents_field,
            reverse_code=reverse_migrate_contents_field,
        ),
    ]
