# Generated by Django 5.0.1 on 2024-07-12 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0015_remove_auser_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('_type', models.CharField(blank=True, max_length=20, null=True)),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('last_edit', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_msgs', to='account.auser')),
                ('mentioned_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentioned_msgs', to='account.auser')),
            ],
        ),
    ]
