# Generated by Django 5.0.1 on 2024-07-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='msg',
            name='self_seen',
            field=models.BooleanField(default=False),
        ),
    ]
