# Generated by Django 5.0.1 on 2024-07-12 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0002_msg_edited_msg_self_seen'),
        ('tool', '0008_rename_channelofio_channelofchat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_msgs', to='tool.channelofchat'),
        ),
    ]
