# Generated by Django 5.0.1 on 2024-08-08 02:23

import django.db.models.deletion
import django.utils.timezone
import project.snowflake
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0016_message_remove_directmessage__type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GMFile',
            fields=[
                ('urlCode', models.PositiveBigIntegerField(db_index=True, default=project.snowflake.AttachmentMFileSnowflakeID, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to='upload/attachment')),
                ('last_url', models.URLField(blank=True, max_length=400, null=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='message.message')),
            ],
        ),
    ]
