# Generated by Django 5.0.1 on 2024-08-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0002_gmfile__type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmfile',
            name='_type',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
    ]
