# Generated by Django 5.0.1 on 2024-08-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0003_alter_gmfile__type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmfile',
            name='_type',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
