# Generated by Django 5.0.1 on 2024-08-09 04:04

import attachment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0004_alter_gmfile__type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmfile',
            name='file',
            field=models.FileField(storage=attachment.models.AttachmentFileSystemStorage, upload_to=attachment.models.MFile.fileSavePath),
        ),
    ]
