# Generated by Django 5.0.1 on 2024-08-09 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0005_alter_gmfile_file'),
        ('message', '0016_message_remove_directmessage__type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GMFile',
            new_name='MFile',
        ),
    ]
