# Generated by Django 5.1.1 on 2024-09-14 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0008_alter_mfile_options'),
        ('message', '0020_alter_message_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfile',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='message.chatmessage'),
        ),
    ]
