# Generated by Django 5.1.1 on 2024-09-14 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0009_alter_mfile_message'),
        ('message', '0020_alter_message_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfile',
            name='state',
            field=models.CharField(choices=[('0', 'pending'), ('1', 'active'), ('2', 'archived')], default='0', max_length=2, verbose_name="\n        type:\n        [\n            ('0', 'pending'),\n            ('1', 'active'),\n            ('2', 'archived')\n        ]\n        "),
        ),
        migrations.AlterField(
            model_name='mfile',
            name='message',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='message.chatmessage'),
            preserve_default=False,
        ),
    ]
